version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
LambdaFunctionName = "lambda1"
stack_name = "lambda2-prod"
s3_bucket = "cloudfront0307"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = 'VPCId=vpc-0b9df6d26c6488729 PrivateSubnetIds=subnet-0bf604215c5364d98,subnet-0a3714e17b138a517 LambdaFunctionName=prod-lambda2 S3BucketName=cloudfront03070204'