version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda"
s3_bucket = "revnue-lambda-artifacts-bucket"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda1"
s3_bucket = "revnue-lambda-artifacts-bucket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []