version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda1-dev"
s3_bucket = "cloudfront0307"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = 'VPCId=vpc-01fd3de3d093b5e68 PrivateSubnetIds=subnet-062c441d4c642daa4,subnet-0fbe4eb8deea2a82b Env=dev LambdaFunctionName=dev-lambda1 S3BucketName=cloudfront0307020405'
