version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
LambdaFunctionName = "lambda1"
stack_name = "lambda1"
s3_bucket = "cloudfront0307"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []

